### ISSUE TITLE
backend model for animal

### ISSUE THREAD

**Issue by AlexanderLeonidasGuenzel** [neuefische/cgn-java-23-2-teamproject-animals#3]

**Comment by AlexanderLeonidasGuenzel** [comment]
##  Tier anlegen

Als ein Mitarbeiter von einem Tierheim
möchte ich ein Tier der Liste hinzufügen können, 
 wenn ein neues Tier ins Tierheim kommt.

## Description

- Eingabefeld mit Hinzufügen und Anzeigen einer Liste, der bereits hinzugefügten Tiere.

## Acceptance criteria

- [ ] Kein leerer Eintrag möglich
- [ ] Angelegte Tiere werden in einer Liste angezeigt
- [ ] Hinweisfenster, wenn kein Eintrag gemacht werden kann.

## Tasks

- [ ] Backend: Model, Repository, Service, Controller
- [ ] Tests: Junit Test, Integrationstest
- [ ] Frontend: Eingabemaske ohne Design
